version: 2
services:
  api:
    build: ./cats-server
    ports:
      - "8000:8000"
    volumes:
      - ./build/libs:/var/cats-api
    depends_on:
      - mongo
      - postgres
      - redis
  mongo:
    image: mongo

  postgres:
    image: postgres

  redis:
    image: redis